# Dockerfile for running a single user jupyter server
FROM ubuntu:15.04

MAINTAINER Ryan May <rmay@ucar.edu>

# Install git and ffmpeg
RUN apt-get update && apt-get -y install git ffmpeg ca-certificates bzip2 curl && apt-get clean
