idv-webcams:
  image: unidata/idv-webcams:latest
  volumes:
    - ./www/:/georesources/webcams/images
  environment:
    - IMAGE_ROOT=CHANGEME!

nginx:
  image: nginx
  volumes:
    - ./www/:/usr/share/nginx/html:ro
  ports:
    # watch out! https://github.com/docker/compose/issues/1259
    - "80:80"
