idv-webcams:
  restart: always
  image: unidata/idv-webcams:latest
  volumes:
    - ~/www/:/georesources/webcams/images/
  environment:
    # something like: http://idv-webcams.cloudapp.net
    - IMAGE_ROOT=CHANGEME!

nginx:
  restart: always
  image: nginx
  volumes:
    - ~/www/:/usr/share/nginx/html:ro
  ports:
    # watch out! https://github.com/docker/compose/issues/1259
    - "80:80"
