###
# LDM
###
ldm:
  # restart: always
  image: unidata/ldm-docker:6.13.6
  container_name: ldm
  # restart: always
  volumes:
    - ~/etc/:/home/ldm/etc/
    - /data/:/home/ldm/var/data/
    - /data/:/data/
    - /data/queues:/home/ldm/var/queues/
    - ~/logs/ldm/:/home/ldm/var/logs/
  ports:
    - "388:388"
  ulimits:
    nofile:
      soft: 64
      hard: 64

###
# Reverse proxy for TDS and RAMADDA
###

traefik:
  image: traefik
  container_name: traefik 
  # restart: always
  command: --web --docker --docker.domain=localhost --accesslogsfile=/log/access_log 
  ports:
    - "80:80"
    - "443:443"
    - "8080:8080"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ~/logs/traefik/:/log/
    - ./files/traefik.toml:/etc/traefik/traefik.toml
    - ./files/:/config/

###
# NGINX
###

nginx:
  image: nginx
  container_name: nginx
  # restart: always
  volumes:
    - ./web/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./web/publish/:/usr/share/nginx/html:ro
  labels:
    - "traefik.backend=nginx"
    - "traefik.frontend.rule=Host:jetstream.unidata.ucar.edu"
    - "traefik.port=80"

###
# RAMADDA
###

ramadda:
  image: unidata/ramadda-docker:2.2
  container_name: ramadda
  # restart: always
  volumes:
    - /repository/:/data/repository/
    - /data/ldm/:/data/ldm/
    - ~/logs/ramadda-tomcat/:/usr/local/tomcat/logs/
    - ~/logs/ramadda/:/data/repository/logs/
  labels:
    - "traefik.backend=ramadda"
    - "traefik.frontend.rule=Host:jetstream.unidata.ucar.edu;PathPrefix:/repository"

###
# THREDDS
###

thredds-production:
  image: unidata/thredds-docker:4.6.8
  container_name: thredds
  # restart: always
  ports:
    - "8443:8443"
  volumes:
    - ~/logs/tds-tomcat/:/usr/local/tomcat/logs/
    - ~/logs/tds/:/usr/local/tomcat/content/thredds/logs/
    - ./files/ssl.crt:/usr/local/tomcat/conf/ssl.crt
    - ./files/ssl.key:/usr/local/tomcat/conf/ssl.key
    - ./files/server.xml:/usr/local/tomcat/conf/server.xml
    - ./files/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
    - ./files/tdsCat.css:/usr/local/tomcat/webapps/thredds/tdsCat.css
    - ./files/folder.gif:/usr/local/tomcat/webapps/thredds/folder.gif
    - /data/:/data/
    - ~/tdsconfig/:/usr/local/tomcat/content/thredds
  labels:
    - "traefik.backend=thredds"
    - "traefik.frontend.rule=Host:jetstream.unidata.ucar.edu;PathPrefix:/thredds"

###
# TDM
###

tdm:
  image: unidata/thredds-docker:tdm-4.6
  container_name: tdm
  # restart: always
  volumes:
      - /data/:/data/
      - ~/tdsconfig/:/usr/local/tomcat/content/thredds/
      - ~/logs/tdm/:/usr/local/tomcat/content/tdm/
  environment:
    # change the password
    - TDM_PW=CHANGEME!
    # that trailing slash is important
    - TDS_HOST=http://jetstream.unidata.ucar.edu/

###
# McIDAS
###
# ADDE, licensing issues that do not allow us to distribute the software via the DockerHub registry. Contact ~support-mcidas@unidata.ucar.edu~ for more information about obtaining this image.

# mcidas:
#   image: unidata/mcidas
#   container_name: mcidas
#   # restart: always
#   volumes:
#     # Directories outside of the container that need to be accessible
#    - ~/mcidas/upcworkdata/:/home/mcidas/upcworkdata/
#    - ~/mcidas/util/:/home/mcidas/util/
#    - ~/mcidas/decoders/:/home/mcidas/decoders/
#    - /data/ldm/pub:/data/ldm/pub/
#   ports:
#    - "112:112"

