###
# LDM
###
ldm:
  image: unidata/ldmtds:latest
  volumes:
    - ~/etc/:/home/ldm/etc/
    - /data/ldm/:/home/ldm/var/data/
    - ~/var/logs/:/home/ldm/var/logs/
  ports:
    - "388:388"

###
# TDM
###

tdm:
  image: unidata/tdm:latest
  volumes:
    - /data/:/data/
    - ~/tdsconfig/:/usr/local/tomcat/content/thredds/
  environment:
    # change the password
    - TDM_PW=CHANGEME!
    # that trailing slash is important
    - TDS_HOST=http://unidata-server.cloudapp.net/

###
# TDS
###
  
tds:
  image: unidata/tds:latest
  volumes:
    - /data/:/data/
    - ~/tdsconfig:/usr/local/tomcat/content/thredds/
    - ~/logs/tds-tomcat/:/usr/local/tomcat/logs/
  ports:
    # TDS Tomcat ports based on server.xml (should not conflict with RAMADDA
    # ports)
    # https://github.com/Unidata/thredds/issues/313
    - "80:8080"
    - "8005:8005"
    - "8080:8080"
    # SSL port for TDM
    - "8443:8443"
    - "8009:8009"

###
# RAMADDA
###

ramadda:
  image: unidata/ramadda:latest
  volumes:
    # Theoretically, it should be possible just to mount data, but then the
    # permissions are screwed up. In particular, the /data/repository directory
    # ends up being owned by root and non-writable by RAMADDA. Mounting the ldm
    # directory for server-side views of data by RAMADDA.
    - /data/repository/:/data/repository/
    - /data/ldm/:/data/ldm/
    - ~/logs/ramadda-tomcat/:/usr/local/tomcat/logs/
  ports:
    # RAMADDA Tomcat ports based on server.xml (should not conflict with TDS
    # ports)
    - "8006:8006"
    - "8081:8081"
    - "8444:8444"
    - "8010:8010"
