tds:
  dockerfile: Dockerfile
  image: unidata/tds:v4.6.3
  ports:
   - "80:8080"
   # SSL port
   - "8443:8443"
  volumes:
  # Some defaults that you will probably want to change
   - ./data/:/data/
   - ./config/:/usr/local/tomcat/content/thredds/
