jupyterhub:
  build: .
  dockerfile: Dockerfile.local
  ports:
   - "8000:8000"
  volumes:
   - /var/run/docker.sock:/var/run/docker.sock
  volumes_from:
   - hub-data

hub-data:
  build: .
  dockerfile: Dockerfile.data

idle-cull:
  build: .
  dockerfile: Dockerfile.idle
  links:
    - jupyterhub
  env_file:
    - jpy_api.env
