FROM unidata/ldm

MAINTAINER Unidata Cloud Team

USER root

###
# Setting up directories and soft links to make TDS container happy
###

RUN mkdir /data

RUN chown -R ldm:ldm /data

USER ldm

RUN ln -s ~/var/data/  /data/ldm

RUN ln -s ~/var/data/ ~/data
