####
# Docker container for building the LDM.
# Using a CentOS base.
#
# See https://www.unidata.ucar.edu/software/ldm/ldm-current/basics/platform.html
####

FROM unidata/ldmbase

###
# Output directory
###

RUN mkdir /tmp/output

###
# Install the ldm
###

COPY install_ldm.sh /home/ldm/

CMD bash -C '/home/ldm/install_ldm.sh';'bash'
